FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY prisma ./prisma
RUN npx prisma generate

COPY tsconfig.json ./
COPY src ./src

RUN npm run build
RUN mkdir -p uploads

EXPOSE 3333

CMD ["sh", "-c", "npm run db:push && npm run db:seed && npm run start"]
